// <copyright file="CustomExceptions.cs" company="Stephen Graham - 011706998">
// Copyright (c) Stephen Graham - 011706998. All rights reserved.
// </copyright>
// <auto-generated/>
namespace Spreadsheet_Stephen_Graham
{
    using System;

    [Serializable]
    public class CustomException : Exception
    {
        public CustomException()
        {
        }

        public CustomException(string message)
            : base(message)
        {
        }

        public CustomException(string message, Exception inner)
            : base(message, inner)
        {
        }

        protected CustomException(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
            : base(info, context)
        {
        }
    }

    [Serializable]
    public class SelfReferenceException : CustomException
    {
        public SelfReferenceException()
        {
        }

        public SelfReferenceException(string message)
            : base(message)
        {
        }

        public SelfReferenceException(string message, Exception inner)
            : base(message, inner)
        {
        }

        protected SelfReferenceException(
            System.Runtime.Serialization.SerializationInfo info,
            System.Runtime.Serialization.StreamingContext context)
            : base(info, context)
        {
        }
    }

    [Serializable]
    public class CircularReferenceException : CustomException
    {
        public CircularReferenceException()
        {
        }

        public CircularReferenceException(string message)
            : base(message)
        {
        }

        public CircularReferenceException(string message, Exception inner)
            : base(message, inner)
        {
        }

        protected CircularReferenceException(
            System.Runtime.Serialization.SerializationInfo info,
            System.Runtime.Serialization.StreamingContext context)
            : base(info, context)
        {
        }
    }
}
